---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
  - My Github:
      - abbr: GH
        href: https://github.com/LukasScarfe
    
  - CloudFlare:
      - abbr: CF
        href: https://dash.cloudflare.com/  

  - Router:
      - abbr: TP
        href: http://192.168.1.1


- Useful Sites:

  - Google Scholar:
        - abbr: GS
          href: https://scholar.google.com/citations?user=_eBW18oAAAAJ&hl=en&oi=ao

  - Lukas Scarfe:
      - abbr: LS
        href: https://lukasscarfe.com

  - Free Media Heck Yeah:
      - abbr: FM
        href: https://fmhy.net/

    