---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Home Automation:
    - Home Assistant:
        icon: home-assistant.png
        href: https://homeassistant.{{HOMEPAGE_VAR_EXPOSED_URL}}
        ping: https://homeassistant.{{HOMEPAGE_VAR_EXPOSED_URL}}
        widget:
            type: homeassistant
            url: "{{HOMEPAGE_VAR_HOMEASSISTANT_URL}}"
            key: "{{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}"
            custom:
                # - state: zone.home
                #   label: People Home
                - state: sensor.bathroom_temp_humidity_sensor_temperature
                  label: Temp
                - state: sensor.living_room_plant_shelf_motion_sensor_illuminance
                  label: Brightness
                - state: light.all_grow_lights
                  label: Grow Lights
                # - state: light.dining_lights
                #   label: Dining Lights
                - state: switch.global_sleep_switches
                  label: Sleep Lights

- Media:
    - Media1:
        - Tautulli:
            icon: tautulli.png
            href: https://tautulli.{{HOMEPAGE_VAR_EXPOSED_URL}}
            # widgetWidth specifically tells the grid how many units to take
            widgetWidth: 2 
            # Adding a Tailwind class is a backup way to force spanning
            classes: col-span-2
            description: Plex Statistics
            container: tautulli
            ping: https://tautulli.{{HOMEPAGE_VAR_EXPOSED_URL}}
            widget:
                type: tautulli
                url: "{{HOMEPAGE_VAR_LOCAL_IP}}:8181"
                key: "{{HOMEPAGE_VAR_TAUTULLI_KEY}}"
                enableUser: true
                showEpisodeNumber: true

        - qBittorrent:
            icon: qbittorrent.png
            href: https://qbit.{{HOMEPAGE_VAR_EXPOSED_URL}}
            description: Torrent Client
            container: qbittorrent
            ping: https://qbit.{{HOMEPAGE_VAR_EXPOSED_URL}}
            widget:
                type: qbittorrent
                url: "{{HOMEPAGE_VAR_LOCAL_IP}}:8484"
                username: "{{HOMEPAGE_VAR_QBIT_USER}}"
                password: "{{HOMEPAGE_VAR_QBIT_PASSWORD}}"


    - Media2:
        - Plex:
            icon: plex.png
            href: https://app.plex.tv/desktop/#!/
            description: Media Server
            container: plex
            server: my-docker
            ping: "{{HOMEPAGE_VAR_LOCAL_IP}}:32400"
            widget:
                type: plex
                url: "{{HOMEPAGE_VAR_LOCAL_IP}}:32400"
                key: "{{HOMEPAGE_VAR_PLEX_KEY}}"
                fields: ["movies", "tv"]

        - Overseerr:
            icon: overseerr.png
            href: https://requests.{{HOMEPAGE_VAR_EXPOSED_URL}}
            description: Media Requests
            container: overseerr
            ping: https://requests.{{HOMEPAGE_VAR_EXPOSED_URL}}
            widget:
                type: overseerr
                url: "{{HOMEPAGE_VAR_LOCAL_IP}}:5055"
                key: "{{HOMEPAGE_VAR_OVERSEER_KEY}}"
                fields: ["processing","approved", "available"]
            
        - Sonarr:
            icon: sonarr.png
            href: https://sonarr.{{HOMEPAGE_VAR_EXPOSED_URL}}
            description: TV Series Management
            container: sonarr
            ping: https://sonarr.{{HOMEPAGE_VAR_EXPOSED_URL}}
            widget:
                type: sonarr
                url: "{{HOMEPAGE_VAR_LOCAL_IP}}:8989"
                key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
                fields: ["wanted", "missing", "series"]
                enableQueue: false

        - Radarr:
            icon: radarr.png
            href: https://radarr.{{HOMEPAGE_VAR_EXPOSED_URL}}
            description: Movie Management
            container: radarr
            ping: https://radarr.{{HOMEPAGE_VAR_EXPOSED_URL}}
            widget:
                type: radarr
                url: "{{HOMEPAGE_VAR_LOCAL_IP}}:7878"
                key: "{{HOMEPAGE_VAR_RADARR_KEY}}"

                fields: ["wanted", "missing", "movies"]
                enableQueue: false

        - Bazarr:
            icon: bazarr.png
            href: https://bazarr.{{HOMEPAGE_VAR_EXPOSED_URL}}
            description: Subtitle Management
            container: bazarr
            ping: https://bazarr.{{HOMEPAGE_VAR_EXPOSED_URL}}
            widget:
                type: bazarr
                url: "{{HOMEPAGE_VAR_LOCAL_IP}}:6767"
                key: "{{HOMEPAGE_VAR_BAZARR_KEY}}"


        - Prowlarr:
            icon: prowlarr.png
            href: https://prowlarr.{{HOMEPAGE_VAR_EXPOSED_URL}}/ 
            description: Indexer Manager
            container: prowlarr
            ping: https://prowlarr.{{HOMEPAGE_VAR_EXPOSED_URL}}
            widget:
                type: prowlarr
                url: "{{HOMEPAGE_VAR_LOCAL_IP}}:9696"
                key: "{{HOMEPAGE_VAR_PROWLARR_KEY}}"
                fields: ["numberOfGrabs", "numberOfQueries"]


        - Agregarr:
            icon: https://raw.githubusercontent.com/agregarr/agregarr/refs/heads/develop/public/android-chrome-512x512.png
            href: https://agregarr.{{HOMEPAGE_VAR_EXPOSED_URL}} 
            description: Plex Collections Manager
            container: agregarr
            server: my-docker
            ping: https://agregarr.{{HOMEPAGE_VAR_EXPOSED_URL}}
            #ping: {{HOMEPAGE_VAR_LOCAL_IP}}:7171

        - Calibre:
            icon: calibre-web.png
            href: https://books.{{HOMEPAGE_VAR_EXPOSED_URL}}
            description: E-book Library
            server: my-docker
            container: calibre
            ping: https://books.{{HOMEPAGE_VAR_EXPOSED_URL}}
            widget:
                type: calibreweb
                url: "{{HOMEPAGE_VAR_LOCAL_IP}}:8083"
                username: "{{HOMEPAGE_VAR_CALIBRE_USER}}"
                password: "{{HOMEPAGE_VAR_CALIBRE_PASSWORD}}"
                fields: ["books", "authors", "series"]

        - Shelfmark:
            icon: https://raw.githubusercontent.com/calibrain/shelfmark/refs/heads/main/src/frontend/public/logo.png
            href: http://bookrequests.{{HOMEPAGE_VAR_EXPOSED_URL}}
            description: E-book Search & Request
            server: my-docker
            container: shelfmark
            ping: http://bookrequests.{{HOMEPAGE_VAR_EXPOSED_URL}}
            #ping: {{HOMEPAGE_VAR_LOCAL_IP}}:8084
    

- Tools:
    - QR Code Generator:
        icon: https://upload.wikimedia.org/wikipedia/commons/3/31/MM_QRcode.png?20120720164609
        href: http://qr.{{HOMEPAGE_VAR_EXPOSED_URL}}
        description: Custom QR Generator
        container: mini-qr
        server: my-docker
        ping: http://qr.{{HOMEPAGE_VAR_EXPOSED_URL}}
    
    - Michelle's Code:
        icon: visual-studio-code.png
        description: Michelle's VSCode Server
        href: https://code.{{HOMEPAGE_VAR_EXPOSED_URL}}
        container: vscode
        ping: https://code.{{HOMEPAGE_VAR_EXPOSED_URL}}
        #ping: {{HOMEPAGE_VAR_LOCAL_IP}}:8443
        showStats: true

    - MeTube:
        icon: metube.png
        href: https://youtube.{{HOMEPAGE_VAR_EXPOSED_URL}}
        description: YouTube Downloader
        server: my-docker
        container: metube
        ping: https://youtube.{{HOMEPAGE_VAR_EXPOSED_URL}}

    - Synology NAS:
        icon: synology.png # Or use a direct URL to a Synology logo
        href: "{{HOMEPAGE_VAR_SYNOLOGY_QUICKCONNECT}}"
        description: Synology QuickConnect
        ping: "{{HOMEPAGE_VAR_SYNOLOGY_QUICKCONNECT}}"

    - Synology Photos:
        icon: synology-photos.png
        # Use your QuickConnect or local IP address
        href: "{{HOMEPAGE_VAR_SYNOLOGY_PHOTOS}}" 
        description: Photo Management & Backup
        ping: "{{HOMEPAGE_VAR_SYNOLOGY_PHOTOS}}" 

    - Speedtest:
        icon: speedtest-tracker.png
        href: https://speedtest.{{HOMEPAGE_VAR_EXPOSED_URL}}
        description: Speedtest Tracker
        container: speedtest-tracker
        ping: https://speedtest.{{HOMEPAGE_VAR_EXPOSED_URL}}
        widget:
            type: speedtest
            url: "{{HOMEPAGE_VAR_LOCAL_IP}}:8013"
            key: "{{HOMEPAGE_VAR_SPEEDTEST_KEY}}"
            version: 2 
            bitratePrecision: 0

    - Mealie:
        icon: mealie.png
        href: https://recipes.{{HOMEPAGE_VAR_EXPOSED_URL}}
        description: Recipe Manager & Planner
        container: mealie
        widget:
            type: mealie
            url: "{{HOMEPAGE_VAR_LOCAL_IP}}:9925"
            key: "{{HOMEPAGE_VAR_MEALIE_KEY}}"
            version: 2
            fields: ["recipes", "users"]

    - Cloudflare:
        icon: cloudflare.png
        href: https://one.dash.cloudflare.com/
        widget:
            type: cloudflared
            accountid: "{{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}"
            tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}}"
            key: "{{HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN}}"



- Weather Center:
    - Weather Radar:
        icon: mdi-weather-radar
        widget:
          type: iframe
          src: https://www.rainviewer.com/map.html?loc=49.183,-122.8249,8&oCS=1&c=3&o=83&lm=1&layer=radar&sm=1&sn=1&ts=2
          classes: h-96 w-full