---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Lukas Scarfe Homepage

favicon: https://raw.githubusercontent.com/LukasScarfe/personal_site/refs/heads/master/static/favicon.ico

disableCollapse: true

iconStyle: theme

background: 
  image: https://wallpapercave.com/wp/wp4183789.jpg
  blur: xs
  saturate: 100
  brightness: 40
  opacity: 25
  
theme: dark
color: slate

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Home Automation:
    style: row
    columns: 1
    header: false

  Media:
    icon: mdi-play-box-multiple-outline
    style: row
    columns: 1

    Media1:
      style: row
      columns: 2
      header: false
    
    Media2:
      style: row
      columns: 3
      header: false

  Tools:
    icon: mdi-tools
    style: row
    columns: 1
    
    
    Tools1:
      style: row
      columns: 4
      header: false

    Tools2:
      style: row
      columns: 2
      header: false

  Research:
    icon: mdi-book-alert
    style: row
    columns: 1


  Weather:
    icon: mdi-weather-partly-snowy-rainy
    style: row
    columns: 1
    