---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Lukas Scarfe Homepage
background: 
  image: https://images.unsplash.com/photo-1476231682828-37e571bc172f?q=80&w=1674&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  blur: sm
  saturate: 100
  brightness: 50
  opacity: 50
  
theme: dark
color: slate

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
