services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      TZ: "America/Toronto"
      EULA: "TRUE"
      TYPE: "FABRIC"
      WHITELIST_ENABLED: "TRUE"
      WHITELIST: "NinjaLlama04,letienne212,Roflcopterz327,asharahmad,NaturalestD"  
      MOTD: "§o§aLukas'§r§6 Server - §l§e Oriole"
      MEMORY: "4G"
      USE_AIKAR_FLAGS: "true"
      #SIMULATION_DISTANCE: "16"
      #VIEW_DISTANCE: "20"
      MODRINTH_PROJECTS: |-
        fabric-api
        lithium
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
    volumes:
      - /home/lukas/Documents/containers/minecraft/data:/data
